[
  {
    name: 'State',
    value: [
      {
        copyright:
          'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2021. All Rights Reserved.',
        roster: [
          '{jerseyNumber: "42", person: {…}, position: {…}}',
          '{jerseyNumber: "45", person: {…}, position: {…}}',
          '{jerseyNumber: "76", person: {…}, position: {…}}',
          '{jerseyNumber: "90", person: {…}, position: {…}}',
          '{jerseyNumber: "41", person: {…}, position: {…}}',
          '{jerseyNumber: "7", person: {…}, position: {…}}',
          '{jerseyNumber: "28", person: {…}, position: {…}}',
          '{jerseyNumber: "11", person: {…}, position: {…}}',
          '{jerseyNumber: "44", person: {…}, position: {…}}',
          '{jerseyNumber: "33", person: {…}, position: {…}}',
          '{jerseyNumber: "71", person: {…}, position: {…}}',
          '{jerseyNumber: "37", person: {…}, position: {…}}',
          '{jerseyNumber: "29", person: {…}, position: {…}}',
          '{jerseyNumber: "83", person: {…}, position: {…}}',
          '{jerseyNumber: "63", person: {…}, position: {…}}',
          '{jerseyNumber: "20", person: {…}, position: {…}}',
          '{jerseyNumber: "13", person: {…}, position: {…}}',
          '{jerseyNumber: "70", person: {…}, position: {…}}',
          '{jerseyNumber: "24", person: {…}, position: {…}}',
          '{jerseyNumber: "86", person: {…}, position: {…}}',
        ],
        link: '/api/v1/teams/1/roster',
      },
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{message: "Object not found", messageNumber: 10}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
      '{copyright: "NHL and the NHL Shield are registered …}',
    ],
    subHooks: [],
    hookSource: {
      lineNumber: 28,
      functionName: 'Stats_Goalies',
      fileName: 'http://localhost:3001/main.0032f1d6918a9730a8ad.hot-update.js',
      columnNumber: 95,
    },
  },
  {
    name: 'Effect',
    value: 'ƒ () {}',
    subHooks: [],
    hookSource: {
      lineNumber: 44,
      functionName: 'Stats_Goalies',
      fileName: 'http://localhost:3001/main.0032f1d6918a9730a8ad.hot-update.js',
      columnNumber: 58,
    },
  },
];
